package sudoku;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.

*/
import java.util.*;
import javax.swing.JOptionPane;
import sudoku.Sudoku1;


/**
 *
 * @author introduccion03
 */
public class Sudoku4 extends javax.swing.JFrame {

    /**
     * Creates new form Sudoku9
     */
    public Sudoku4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos30 = new javax.swing.JTextField();
        pos31 = new javax.swing.JTextField();
        pos19 = new javax.swing.JTextField();
        pos20 = new javax.swing.JTextField();
        pos21 = new javax.swing.JTextField();
        pos22 = new javax.swing.JTextField();
        Limpiar = new javax.swing.JButton();
        Resolver = new javax.swing.JButton();
        pos4 = new javax.swing.JTextField();
        pos3 = new javax.swing.JTextField();
        pos2 = new javax.swing.JTextField();
        pos29 = new javax.swing.JTextField();
        pos1 = new javax.swing.JTextField();
        pos28 = new javax.swing.JTextField();
        pos12 = new javax.swing.JTextField();
        pos13 = new javax.swing.JTextField();
        pos10 = new javax.swing.JTextField();
        pos11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 200));

        pos30.setBackground(new java.awt.Color(100, 100, 100));
        pos30.setForeground(new java.awt.Color(255, 255, 255));
        pos30.setText("0");
        pos30.setAlignmentX(0.6F);
        pos30.setCaretColor(new java.awt.Color(255, 255, 255));
        pos30.setMaximumSize(new java.awt.Dimension(1, 1));
        pos30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos30ActionPerformed(evt);
            }
        });

        pos31.setBackground(new java.awt.Color(100, 100, 100));
        pos31.setForeground(new java.awt.Color(255, 255, 255));
        pos31.setText("0");
        pos31.setAlignmentX(0.6F);
        pos31.setCaretColor(new java.awt.Color(255, 255, 255));
        pos31.setMaximumSize(new java.awt.Dimension(1, 1));

        pos19.setBackground(new java.awt.Color(100, 100, 100));
        pos19.setForeground(new java.awt.Color(255, 255, 255));
        pos19.setText("0");
        pos19.setAlignmentX(0.6F);
        pos19.setCaretColor(new java.awt.Color(255, 255, 255));
        pos19.setMaximumSize(new java.awt.Dimension(1, 1));
        pos19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos19ActionPerformed(evt);
            }
        });

        pos20.setBackground(new java.awt.Color(100, 100, 100));
        pos20.setForeground(new java.awt.Color(255, 255, 255));
        pos20.setText("0");
        pos20.setAlignmentX(0.6F);
        pos20.setCaretColor(new java.awt.Color(255, 255, 255));
        pos20.setMaximumSize(new java.awt.Dimension(1, 1));

        pos21.setBackground(new java.awt.Color(100, 100, 100));
        pos21.setForeground(new java.awt.Color(255, 255, 255));
        pos21.setText("0");
        pos21.setAlignmentX(0.6F);
        pos21.setCaretColor(new java.awt.Color(255, 255, 255));
        pos21.setMaximumSize(new java.awt.Dimension(1, 1));

        pos22.setBackground(new java.awt.Color(100, 100, 100));
        pos22.setForeground(new java.awt.Color(255, 255, 255));
        pos22.setText("0");
        pos22.setAlignmentX(0.6F);
        pos22.setCaretColor(new java.awt.Color(255, 255, 255));
        pos22.setMaximumSize(new java.awt.Dimension(1, 1));
        pos22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos22ActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        Resolver.setText("Resolver");
        Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolverActionPerformed(evt);
            }
        });

        pos4.setBackground(new java.awt.Color(100, 100, 100));
        pos4.setForeground(new java.awt.Color(255, 255, 255));
        pos4.setText("0");
        pos4.setAlignmentX(0.6F);
        pos4.setCaretColor(new java.awt.Color(255, 255, 255));
        pos4.setMaximumSize(new java.awt.Dimension(1, 1));

        pos3.setBackground(new java.awt.Color(100, 100, 100));
        pos3.setForeground(new java.awt.Color(255, 255, 255));
        pos3.setText("0");
        pos3.setAlignmentX(0.6F);
        pos3.setCaretColor(new java.awt.Color(255, 255, 255));
        pos3.setMaximumSize(new java.awt.Dimension(1, 1));

        pos2.setBackground(new java.awt.Color(100, 100, 100));
        pos2.setForeground(new java.awt.Color(255, 255, 255));
        pos2.setText("0");
        pos2.setAlignmentX(0.6F);
        pos2.setCaretColor(new java.awt.Color(255, 255, 255));
        pos2.setMaximumSize(new java.awt.Dimension(1, 1));

        pos29.setBackground(new java.awt.Color(100, 100, 100));
        pos29.setForeground(new java.awt.Color(255, 255, 255));
        pos29.setText("0");
        pos29.setAlignmentX(0.6F);
        pos29.setCaretColor(new java.awt.Color(255, 255, 255));
        pos29.setMaximumSize(new java.awt.Dimension(1, 1));

        pos1.setBackground(new java.awt.Color(100, 100, 100));
        pos1.setForeground(new java.awt.Color(255, 255, 255));
        pos1.setText("0");
        pos1.setAlignmentX(0.6F);
        pos1.setCaretColor(new java.awt.Color(255, 255, 255));
        pos1.setMaximumSize(new java.awt.Dimension(1, 1));

        pos28.setBackground(new java.awt.Color(100, 100, 100));
        pos28.setForeground(new java.awt.Color(255, 255, 255));
        pos28.setText("0");
        pos28.setAlignmentX(0.6F);
        pos28.setCaretColor(new java.awt.Color(255, 255, 255));
        pos28.setMaximumSize(new java.awt.Dimension(1, 1));

        pos12.setBackground(new java.awt.Color(100, 100, 100));
        pos12.setForeground(new java.awt.Color(255, 255, 255));
        pos12.setText("0");
        pos12.setAlignmentX(0.6F);
        pos12.setCaretColor(new java.awt.Color(255, 255, 255));
        pos12.setMaximumSize(new java.awt.Dimension(1, 1));

        pos13.setBackground(new java.awt.Color(100, 100, 100));
        pos13.setForeground(new java.awt.Color(255, 255, 255));
        pos13.setText("0");
        pos13.setAlignmentX(0.6F);
        pos13.setCaretColor(new java.awt.Color(255, 255, 255));
        pos13.setMaximumSize(new java.awt.Dimension(1, 1));

        pos10.setBackground(new java.awt.Color(100, 100, 100));
        pos10.setForeground(new java.awt.Color(255, 255, 255));
        pos10.setText("0");
        pos10.setAlignmentX(0.6F);
        pos10.setCaretColor(new java.awt.Color(255, 255, 255));
        pos10.setMaximumSize(new java.awt.Dimension(1, 1));

        pos11.setBackground(new java.awt.Color(100, 100, 100));
        pos11.setForeground(new java.awt.Color(255, 255, 255));
        pos11.setText("0");
        pos11.setAlignmentX(0.6F);
        pos11.setCaretColor(new java.awt.Color(255, 255, 255));
        pos11.setMaximumSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Resolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpiar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
protected JOptionPane mensaje=new JOptionPane();
    private void pos30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos30ActionPerformed

    private void pos19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos19ActionPerformed

    private void pos22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos22ActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        pos1.setText("0");
        pos2.setText("0");
        pos3.setText("0");
        pos4.setText("0");
       
        pos10.setText("0");
        pos11.setText("0");
        pos12.setText("0");
        pos13.setText("0");
        
        pos19.setText("0");
        pos20.setText("0");
        pos21.setText("0");
        pos22.setText("0");
        
        pos28.setText("0");
        pos29.setText("0");
        pos30.setText("0");
        pos31.setText("0");
       
                        
        
    }//GEN-LAST:event_LimpiarActionPerformed

    private void ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolverActionPerformed
      Sudoku1 s=new Sudoku1();
 try{
      int [][]A={
        {Integer.parseInt(pos1.getText()), Integer.parseInt(pos2.getText()), Integer.parseInt(pos3.getText()), Integer.parseInt(pos4.getText())},
        {Integer.parseInt(pos10.getText()), Integer.parseInt(pos11.getText()), Integer.parseInt(pos12.getText()), Integer.parseInt(pos13.getText())},
        {Integer.parseInt(pos19.getText()), Integer.parseInt(pos20.getText()), Integer.parseInt(pos21.getText()), Integer.parseInt(pos22.getText()), },
        {Integer.parseInt(pos28.getText()), Integer.parseInt(pos29.getText()), Integer.parseInt(pos30.getText()), Integer.parseInt(pos31.getText())},
      
      };
 }catch(NumberFormatException e){
     mensaje.showMessageDialog(Resolver,"Error no ingresar texto",null,mensaje.ERROR_MESSAGE);
 }
 int [][]A={
        {Integer.parseInt(pos1.getText()), Integer.parseInt(pos2.getText()), Integer.parseInt(pos3.getText()), Integer.parseInt(pos4.getText())},
        {Integer.parseInt(pos10.getText()), Integer.parseInt(pos11.getText()), Integer.parseInt(pos12.getText()), Integer.parseInt(pos13.getText())},
        {Integer.parseInt(pos19.getText()), Integer.parseInt(pos20.getText()), Integer.parseInt(pos21.getText()), Integer.parseInt(pos22.getText()), },
        {Integer.parseInt(pos28.getText()), Integer.parseInt(pos29.getText()), Integer.parseInt(pos30.getText()), Integer.parseInt(pos31.getText())},
      
      };
     
      if(s.ValidaInicio(A)==false)
          mensaje.showMessageDialog(Resolver,"Error. Ponga números dentro de rango.",null,mensaje.ERROR_MESSAGE);
      else     
          
      s.llena(A, 0, 0, 1);
      pos1.setText(A[0][0]+"");
      pos2.setText(A[0][1]+"");
      pos3.setText(A[0][2]+"");
      pos4.setText(A[0][3]+""); 
      pos10.setText(A[1][0]+"");
      pos11.setText(A[1][1]+"");
      pos12.setText(A[1][2]+"");
      pos13.setText(A[1][3]+"");
      pos19.setText(A[2][0]+"");
      pos20.setText(A[2][1]+"");
      pos21.setText(A[2][2]+"");
      pos22.setText(A[2][3]+"");
      pos28.setText(A[3][0]+"");
      pos29.setText(A[3][1]+"");
      pos30.setText(A[3][2]+"");
      pos31.setText(A[3][3]+"");
      
            
    }//GEN-LAST:event_ResolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Resolver;
    private javax.swing.JTextField pos1;
    private javax.swing.JTextField pos10;
    private javax.swing.JTextField pos11;
    private javax.swing.JTextField pos12;
    private javax.swing.JTextField pos13;
    private javax.swing.JTextField pos19;
    private javax.swing.JTextField pos2;
    private javax.swing.JTextField pos20;
    private javax.swing.JTextField pos21;
    private javax.swing.JTextField pos22;
    private javax.swing.JTextField pos28;
    private javax.swing.JTextField pos29;
    private javax.swing.JTextField pos3;
    private javax.swing.JTextField pos30;
    private javax.swing.JTextField pos31;
    private javax.swing.JTextField pos4;
    // End of variables declaration//GEN-END:variables
}
