package sudoku;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.

*/
import java.util.*;
import sudoku.Sudoku1;
package sudoku;

/**
 *
 * @author introduccion03
 */
public class Sudoku9 extends javax.swing.JFrame {

    /**
     * Creates new form Sudoku9
     */
    public Sudoku9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pos76 = new javax.swing.JTextField();
        pos75 = new javax.swing.JTextField();
        pos74 = new javax.swing.JTextField();
        pos32 = new javax.swing.JTextField();
        pos33 = new javax.swing.JTextField();
        pos30 = new javax.swing.JTextField();
        pos31 = new javax.swing.JTextField();
        pos36 = new javax.swing.JTextField();
        pos34 = new javax.swing.JTextField();
        pos35 = new javax.swing.JTextField();
        pos40 = new javax.swing.JTextField();
        pos39 = new javax.swing.JTextField();
        pos38 = new javax.swing.JTextField();
        pos37 = new javax.swing.JTextField();
        pos79 = new javax.swing.JTextField();
        pos80 = new javax.swing.JTextField();
        pos77 = new javax.swing.JTextField();
        pos78 = new javax.swing.JTextField();
        pos81 = new javax.swing.JTextField();
        pos64 = new javax.swing.JTextField();
        pos63 = new javax.swing.JTextField();
        pos66 = new javax.swing.JTextField();
        pos65 = new javax.swing.JTextField();
        pos19 = new javax.swing.JTextField();
        pos20 = new javax.swing.JTextField();
        pos21 = new javax.swing.JTextField();
        pos22 = new javax.swing.JTextField();
        pos23 = new javax.swing.JTextField();
        pos24 = new javax.swing.JTextField();
        pos25 = new javax.swing.JTextField();
        pos26 = new javax.swing.JTextField();
        Limpiar = new javax.swing.JButton();
        Resolver = new javax.swing.JButton();
        pos4 = new javax.swing.JTextField();
        pos27 = new javax.swing.JTextField();
        pos3 = new javax.swing.JTextField();
        pos2 = new javax.swing.JTextField();
        pos29 = new javax.swing.JTextField();
        pos1 = new javax.swing.JTextField();
        pos28 = new javax.swing.JTextField();
        pos67 = new javax.swing.JTextField();
        pos68 = new javax.swing.JTextField();
        pos6 = new javax.swing.JTextField();
        pos69 = new javax.swing.JTextField();
        pos5 = new javax.swing.JTextField();
        pos70 = new javax.swing.JTextField();
        pos71 = new javax.swing.JTextField();
        pos72 = new javax.swing.JTextField();
        pos73 = new javax.swing.JTextField();
        pos56 = new javax.swing.JTextField();
        pos55 = new javax.swing.JTextField();
        pos54 = new javax.swing.JTextField();
        pos53 = new javax.swing.JTextField();
        pos16 = new javax.swing.JTextField();
        pos52 = new javax.swing.JTextField();
        pos14 = new javax.swing.JTextField();
        pos15 = new javax.swing.JTextField();
        pos12 = new javax.swing.JTextField();
        pos13 = new javax.swing.JTextField();
        pos10 = new javax.swing.JTextField();
        pos11 = new javax.swing.JTextField();
        pos8 = new javax.swing.JTextField();
        pos9 = new javax.swing.JTextField();
        pos18 = new javax.swing.JTextField();
        pos17 = new javax.swing.JTextField();
        pos61 = new javax.swing.JTextField();
        pos62 = new javax.swing.JTextField();
        pos59 = new javax.swing.JTextField();
        pos60 = new javax.swing.JTextField();
        pos57 = new javax.swing.JTextField();
        pos58 = new javax.swing.JTextField();
        pos46 = new javax.swing.JTextField();
        pos45 = new javax.swing.JTextField();
        pos42 = new javax.swing.JTextField();
        pos41 = new javax.swing.JTextField();
        pos44 = new javax.swing.JTextField();
        pos43 = new javax.swing.JTextField();
        pos7 = new javax.swing.JTextField();
        pos48 = new javax.swing.JTextField();
        pos49 = new javax.swing.JTextField();
        pos50 = new javax.swing.JTextField();
        pos51 = new javax.swing.JTextField();
        pos47 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pos76.setText("76");
        pos76.setAlignmentX(0.6F);
        pos76.setMaximumSize(new java.awt.Dimension(1, 1));

        pos75.setText("75");
        pos75.setAlignmentX(0.6F);
        pos75.setMaximumSize(new java.awt.Dimension(1, 1));

        pos74.setText("74");
        pos74.setAlignmentX(0.6F);
        pos74.setMaximumSize(new java.awt.Dimension(1, 1));

        pos32.setText("32");
        pos32.setAlignmentX(0.6F);
        pos32.setMaximumSize(new java.awt.Dimension(1, 1));

        pos33.setText("33");
        pos33.setAlignmentX(0.6F);
        pos33.setMaximumSize(new java.awt.Dimension(1, 1));

        pos30.setText("30");
        pos30.setAlignmentX(0.6F);
        pos30.setMaximumSize(new java.awt.Dimension(1, 1));
        pos30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos30ActionPerformed(evt);
            }
        });

        pos31.setText("31");
        pos31.setAlignmentX(0.6F);
        pos31.setMaximumSize(new java.awt.Dimension(1, 1));

        pos36.setText("36");
        pos36.setAlignmentX(0.6F);
        pos36.setMaximumSize(new java.awt.Dimension(1, 1));
        pos36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos36ActionPerformed(evt);
            }
        });

        pos34.setText("34");
        pos34.setAlignmentX(0.6F);
        pos34.setMaximumSize(new java.awt.Dimension(1, 1));
        pos34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos34ActionPerformed(evt);
            }
        });

        pos35.setText("35");
        pos35.setAlignmentX(0.6F);
        pos35.setMaximumSize(new java.awt.Dimension(1, 1));
        pos35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos35ActionPerformed(evt);
            }
        });

        pos40.setText("40");
        pos40.setAlignmentX(0.6F);
        pos40.setMaximumSize(new java.awt.Dimension(1, 1));

        pos39.setText("39");
        pos39.setAlignmentX(0.6F);
        pos39.setMaximumSize(new java.awt.Dimension(1, 1));

        pos38.setText("38");
        pos38.setAlignmentX(0.6F);
        pos38.setMaximumSize(new java.awt.Dimension(1, 1));

        pos37.setText("37");
        pos37.setAlignmentX(0.6F);
        pos37.setMaximumSize(new java.awt.Dimension(1, 1));

        pos79.setText("79");
        pos79.setAlignmentX(0.6F);
        pos79.setMaximumSize(new java.awt.Dimension(1, 1));

        pos80.setText("80");
        pos80.setAlignmentX(0.6F);
        pos80.setMaximumSize(new java.awt.Dimension(1, 1));

        pos77.setText("77");
        pos77.setAlignmentX(0.6F);
        pos77.setMaximumSize(new java.awt.Dimension(1, 1));

        pos78.setText("78");
        pos78.setAlignmentX(0.6F);
        pos78.setMaximumSize(new java.awt.Dimension(1, 1));

        pos81.setText("81");
        pos81.setAlignmentX(0.6F);
        pos81.setMaximumSize(new java.awt.Dimension(1, 1));

        pos64.setText("64");
        pos64.setAlignmentX(0.6F);
        pos64.setMaximumSize(new java.awt.Dimension(1, 1));

        pos63.setText("63");
        pos63.setAlignmentX(0.6F);
        pos63.setMaximumSize(new java.awt.Dimension(1, 1));

        pos66.setText("66");
        pos66.setAlignmentX(0.6F);
        pos66.setMaximumSize(new java.awt.Dimension(1, 1));

        pos65.setText("65");
        pos65.setAlignmentX(0.6F);
        pos65.setMaximumSize(new java.awt.Dimension(1, 1));

        pos19.setText("19");
        pos19.setAlignmentX(0.6F);
        pos19.setMaximumSize(new java.awt.Dimension(1, 1));
        pos19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos19ActionPerformed(evt);
            }
        });

        pos20.setText("20");
        pos20.setAlignmentX(0.6F);
        pos20.setMaximumSize(new java.awt.Dimension(1, 1));

        pos21.setText("21");
        pos21.setAlignmentX(0.6F);
        pos21.setMaximumSize(new java.awt.Dimension(1, 1));

        pos22.setText("22");
        pos22.setAlignmentX(0.6F);
        pos22.setMaximumSize(new java.awt.Dimension(1, 1));
        pos22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos22ActionPerformed(evt);
            }
        });

        pos23.setText("23");
        pos23.setAlignmentX(0.6F);
        pos23.setMaximumSize(new java.awt.Dimension(1, 1));

        pos24.setText("24");
        pos24.setAlignmentX(0.6F);
        pos24.setMaximumSize(new java.awt.Dimension(1, 1));

        pos25.setText("25");
        pos25.setAlignmentX(0.6F);
        pos25.setMaximumSize(new java.awt.Dimension(1, 1));
        pos25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos25ActionPerformed(evt);
            }
        });

        pos26.setText("26");
        pos26.setAlignmentX(0.6F);
        pos26.setMaximumSize(new java.awt.Dimension(1, 1));
        pos26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos26ActionPerformed(evt);
            }
        });

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        Resolver.setText("Resolver");
        Resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResolverActionPerformed(evt);
            }
        });

        pos4.setText("4");
        pos4.setAlignmentX(0.6F);
        pos4.setMaximumSize(new java.awt.Dimension(1, 1));

        pos27.setText("27");
        pos27.setAlignmentX(0.6F);
        pos27.setMaximumSize(new java.awt.Dimension(1, 1));
        pos27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos27ActionPerformed(evt);
            }
        });

        pos3.setText("3");
        pos3.setAlignmentX(0.6F);
        pos3.setMaximumSize(new java.awt.Dimension(1, 1));

        pos2.setText("2");
        pos2.setAlignmentX(0.6F);
        pos2.setMaximumSize(new java.awt.Dimension(1, 1));

        pos29.setText("29");
        pos29.setAlignmentX(0.6F);
        pos29.setMaximumSize(new java.awt.Dimension(1, 1));

        pos1.setText("1");
        pos1.setAlignmentX(0.6F);
        pos1.setMaximumSize(new java.awt.Dimension(1, 1));

        pos28.setText("28");
        pos28.setAlignmentX(0.6F);
        pos28.setMaximumSize(new java.awt.Dimension(1, 1));

        pos67.setText("67");
        pos67.setAlignmentX(0.6F);
        pos67.setMaximumSize(new java.awt.Dimension(1, 1));

        pos68.setText("68");
        pos68.setAlignmentX(0.6F);
        pos68.setMaximumSize(new java.awt.Dimension(1, 1));

        pos6.setText("6");
        pos6.setAlignmentX(0.6F);
        pos6.setMaximumSize(new java.awt.Dimension(1, 1));

        pos69.setText("69");
        pos69.setAlignmentX(0.6F);
        pos69.setMaximumSize(new java.awt.Dimension(1, 1));
        pos69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos69ActionPerformed(evt);
            }
        });

        pos5.setText("5");
        pos5.setAlignmentX(0.6F);
        pos5.setMaximumSize(new java.awt.Dimension(1, 1));

        pos70.setText("70");
        pos70.setAlignmentX(0.6F);
        pos70.setMaximumSize(new java.awt.Dimension(1, 1));

        pos71.setText("71");
        pos71.setAlignmentX(0.6F);
        pos71.setMaximumSize(new java.awt.Dimension(1, 1));

        pos72.setText("72");
        pos72.setAlignmentX(0.6F);
        pos72.setMaximumSize(new java.awt.Dimension(1, 1));

        pos73.setText("73");
        pos73.setAlignmentX(0.6F);
        pos73.setMaximumSize(new java.awt.Dimension(1, 1));

        pos56.setText("56");
        pos56.setAlignmentX(0.6F);
        pos56.setMaximumSize(new java.awt.Dimension(1, 1));

        pos55.setText("55");
        pos55.setAlignmentX(0.6F);
        pos55.setMaximumSize(new java.awt.Dimension(1, 1));

        pos54.setText("54");
        pos54.setAlignmentX(0.6F);
        pos54.setMaximumSize(new java.awt.Dimension(1, 1));
        pos54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos54ActionPerformed(evt);
            }
        });

        pos53.setText("53");
        pos53.setAlignmentX(0.6F);
        pos53.setMaximumSize(new java.awt.Dimension(1, 1));

        pos16.setText("16");
        pos16.setAlignmentX(0.6F);
        pos16.setMaximumSize(new java.awt.Dimension(1, 1));

        pos52.setText("52");
        pos52.setAlignmentX(0.6F);
        pos52.setMaximumSize(new java.awt.Dimension(1, 1));

        pos14.setText("14");
        pos14.setAlignmentX(0.6F);
        pos14.setMaximumSize(new java.awt.Dimension(1, 1));

        pos15.setText("15");
        pos15.setAlignmentX(0.6F);
        pos15.setMaximumSize(new java.awt.Dimension(1, 1));

        pos12.setText("12");
        pos12.setAlignmentX(0.6F);
        pos12.setMaximumSize(new java.awt.Dimension(1, 1));

        pos13.setText("13");
        pos13.setAlignmentX(0.6F);
        pos13.setMaximumSize(new java.awt.Dimension(1, 1));

        pos10.setText("10");
        pos10.setAlignmentX(0.6F);
        pos10.setMaximumSize(new java.awt.Dimension(1, 1));

        pos11.setText("11");
        pos11.setAlignmentX(0.6F);
        pos11.setMaximumSize(new java.awt.Dimension(1, 1));

        pos8.setText("8");
        pos8.setAlignmentX(0.6F);
        pos8.setMaximumSize(new java.awt.Dimension(1, 1));

        pos9.setText("9");
        pos9.setAlignmentX(0.6F);
        pos9.setMaximumSize(new java.awt.Dimension(1, 1));

        pos18.setText("18");
        pos18.setAlignmentX(0.6F);
        pos18.setMaximumSize(new java.awt.Dimension(1, 1));

        pos17.setText("17");
        pos17.setAlignmentX(0.6F);
        pos17.setMaximumSize(new java.awt.Dimension(1, 1));

        pos61.setText("61");
        pos61.setAlignmentX(0.6F);
        pos61.setMaximumSize(new java.awt.Dimension(1, 1));

        pos62.setText("62");
        pos62.setAlignmentX(0.6F);
        pos62.setMaximumSize(new java.awt.Dimension(1, 1));

        pos59.setText("59");
        pos59.setAlignmentX(0.6F);
        pos59.setMaximumSize(new java.awt.Dimension(1, 1));

        pos60.setText("60");
        pos60.setAlignmentX(0.6F);
        pos60.setMaximumSize(new java.awt.Dimension(1, 1));

        pos57.setText("57");
        pos57.setAlignmentX(0.6F);
        pos57.setMaximumSize(new java.awt.Dimension(1, 1));

        pos58.setText("58");
        pos58.setAlignmentX(0.6F);
        pos58.setMaximumSize(new java.awt.Dimension(1, 1));

        pos46.setText("46");
        pos46.setAlignmentX(0.6F);
        pos46.setMaximumSize(new java.awt.Dimension(1, 1));

        pos45.setText("45");
        pos45.setAlignmentX(0.6F);
        pos45.setMaximumSize(new java.awt.Dimension(1, 1));

        pos42.setText("42");
        pos42.setAlignmentX(0.6F);
        pos42.setMaximumSize(new java.awt.Dimension(1, 1));

        pos41.setText("41");
        pos41.setAlignmentX(0.6F);
        pos41.setMaximumSize(new java.awt.Dimension(1, 1));

        pos44.setText("44");
        pos44.setAlignmentX(0.6F);
        pos44.setMaximumSize(new java.awt.Dimension(1, 1));

        pos43.setText("43");
        pos43.setAlignmentX(0.6F);
        pos43.setMaximumSize(new java.awt.Dimension(1, 1));

        pos7.setText("7");
        pos7.setAlignmentX(0.6F);
        pos7.setMaximumSize(new java.awt.Dimension(1, 1));

        pos48.setText("48");
        pos48.setAlignmentX(0.6F);
        pos48.setMaximumSize(new java.awt.Dimension(1, 1));

        pos49.setText("49");
        pos49.setAlignmentX(0.6F);
        pos49.setMaximumSize(new java.awt.Dimension(1, 1));

        pos50.setText("50");
        pos50.setAlignmentX(0.6F);
        pos50.setMaximumSize(new java.awt.Dimension(1, 1));

        pos51.setText("51");
        pos51.setAlignmentX(0.6F);
        pos51.setMaximumSize(new java.awt.Dimension(1, 1));
        pos51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos51ActionPerformed(evt);
            }
        });

        pos47.setText("47");
        pos47.setAlignmentX(0.6F);
        pos47.setMaximumSize(new java.awt.Dimension(1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pos7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pos9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos36, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos40, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos41, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos42, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos43, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos44, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos46, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos47, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos48, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos49, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos50, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos51, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos52, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos53, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos54, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos55, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos56, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos57, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos58, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos59, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos60, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos61, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos62, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos63, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos64, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos65, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos66, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos67, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos68, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos69, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos70, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos71, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos72, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos73, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos74, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos75, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos76, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos77, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos78, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos79, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos80, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos81, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pos16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pos18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Resolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Limpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos67, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos69, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos70, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos72, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos73, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos74, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos75, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos76, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos78, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pos30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos30ActionPerformed

    private void pos36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos36ActionPerformed

    private void pos34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos34ActionPerformed

    private void pos35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos35ActionPerformed

    private void pos19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos19ActionPerformed

    private void pos22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos22ActionPerformed

    private void pos25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos25ActionPerformed

    private void pos26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos26ActionPerformed

    private void pos27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos27ActionPerformed

    private void pos69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos69ActionPerformed

    private void pos54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos54ActionPerformed

    private void pos51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos51ActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        pos1.setText("0");
        pos2.setText("0");
        pos3.setText("0");
        pos4.setText("0");
        pos5.setText("0"); 
        pos6.setText("0");
        pos7.setText("0");
        pos8.setText("0");
        pos9.setText("0");
        pos10.setText("0");
        pos11.setText("0");
        pos12.setText("0");
        pos13.setText("0");
        pos14.setText("0");
        pos15.setText("0"); 
        pos16.setText("0");
        pos17.setText("0");
        pos18.setText("0");
        pos19.setText("0");
        pos20.setText("0");
        pos21.setText("0");
        pos22.setText("0");
        pos23.setText("0");
        pos24.setText("0");
        pos25.setText("0"); 
        pos26.setText("0");
        pos27.setText("0");
        pos28.setText("0");
        pos29.setText("0");
        pos30.setText("0");
        pos31.setText("0");
        pos32.setText("0");
        pos33.setText("0");
        pos34.setText("0");
        pos35.setText("0"); 
        pos36.setText("0");
        pos37.setText("0");
        pos38.setText("0");
        pos39.setText("0");
        pos40.setText("0");
        pos41.setText("0");
        pos42.setText("0");
        pos43.setText("0");
        pos44.setText("0");
        pos45.setText("0"); 
        pos46.setText("0");
        pos47.setText("0");
        pos48.setText("0");
        pos49.setText("0");
        pos50.setText("0");
        pos51.setText("0");
        pos52.setText("0");
        pos53.setText("0");
        pos54.setText("0");
        pos55.setText("0"); 
        pos56.setText("0");
        pos57.setText("0");
        pos58.setText("0");
        pos59.setText("0");
        pos60.setText("0");
        pos61.setText("0");
        pos62.setText("0");
        pos63.setText("0");
        pos64.setText("0");
        pos65.setText("0"); 
        pos66.setText("0");
        pos67.setText("0");
        pos68.setText("0");
        pos69.setText("0");
        pos70.setText("0");
        pos71.setText("0");
        pos72.setText("0");
        pos73.setText("0");
        pos74.setText("0");
        pos75.setText("0"); 
        pos76.setText("0");
        pos77.setText("0");
        pos78.setText("0");
        pos79.setText("0");
        pos80.setText("0");
        pos81.setText("0");
                        
        
    }//GEN-LAST:event_LimpiarActionPerformed

    private void ResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResolverActionPerformed
      Sudoku1 s=new Sudoku1();
 
      int [][]A={
          
        {Integer.parseInt(pos1.getText()), Integer.parseInt(pos2.getText()), Integer.parseInt(pos3.getText()), Integer.parseInt(pos4.getText()), Integer.parseInt(pos5.getText()), Integer.parseInt(pos6.getText()), Integer.parseInt(pos7.getText()), Integer.parseInt(pos8.getText()), Integer.parseInt(pos9.getText())},
        {Integer.parseInt(pos10.getText()), Integer.parseInt(pos11.getText()), Integer.parseInt(pos12.getText()), Integer.parseInt(pos13.getText()), Integer.parseInt(pos14.getText()), Integer.parseInt(pos15.getText()), Integer.parseInt(pos16.getText()), Integer.parseInt(pos17.getText()), Integer.parseInt(pos18.getText())},
        {Integer.parseInt(pos19.getText()), Integer.parseInt(pos20.getText()), Integer.parseInt(pos21.getText()), Integer.parseInt(pos22.getText()), Integer.parseInt(pos23.getText()), Integer.parseInt(pos24.getText()), Integer.parseInt(pos25.getText()), Integer.parseInt(pos26.getText()), Integer.parseInt(pos27.getText())},
        {Integer.parseInt(pos28.getText()), Integer.parseInt(pos29.getText()), Integer.parseInt(pos30.getText()), Integer.parseInt(pos31.getText()), Integer.parseInt(pos32.getText()), Integer.parseInt(pos33.getText()), Integer.parseInt(pos34.getText()), Integer.parseInt(pos35.getText()), Integer.parseInt(pos36.getText())},
        {Integer.parseInt(pos37.getText()), Integer.parseInt(pos38.getText()), Integer.parseInt(pos39.getText()), Integer.parseInt(pos40.getText()), Integer.parseInt(pos41.getText()), Integer.parseInt(pos42.getText()), Integer.parseInt(pos43.getText()), Integer.parseInt(pos44.getText()), Integer.parseInt(pos45.getText())},
        {Integer.parseInt(pos46.getText()), Integer.parseInt(pos47.getText()), Integer.parseInt(pos48.getText()), Integer.parseInt(pos49.getText()), Integer.parseInt(pos50.getText()), Integer.parseInt(pos51.getText()), Integer.parseInt(pos52.getText()), Integer.parseInt(pos53.getText()), Integer.parseInt(pos54.getText())},
        {Integer.parseInt(pos55.getText()), Integer.parseInt(pos56.getText()), Integer.parseInt(pos57.getText()), Integer.parseInt(pos58.getText()), Integer.parseInt(pos59.getText()), Integer.parseInt(pos60.getText()), Integer.parseInt(pos61.getText()), Integer.parseInt(pos62.getText()), Integer.parseInt(pos63.getText())},
        {Integer.parseInt(pos64.getText()), Integer.parseInt(pos65.getText()), Integer.parseInt(pos66.getText()), Integer.parseInt(pos67.getText()), Integer.parseInt(pos68.getText()), Integer.parseInt(pos69.getText()), Integer.parseInt(pos70.getText()), Integer.parseInt(pos71.getText()), Integer.parseInt(pos72.getText())},
        {Integer.parseInt(pos73.getText()), Integer.parseInt(pos74.getText()), Integer.parseInt(pos75.getText()), Integer.parseInt(pos76.getText()), Integer.parseInt(pos77.getText()), Integer.parseInt(pos78.getText()), Integer.parseInt(pos79.getText()), Integer.parseInt(pos80.getText()), Integer.parseInt(pos81.getText())},
      };
      //if(s.ValidaInicio(A, 0, 0,1)) 
          s.llena(A, 0, 0, 1);
      pos1.setText(A[0][0]+"");
      pos2.setText(A[0][1]+"");
      pos3.setText(A[0][2]+"");
      pos4.setText(A[0][3]+""); 
      pos5.setText(A[0][4]+"");
      pos6.setText(A[0][5]+"");
      pos7.setText(A[0][6]+"");
      pos8.setText(A[0][7]+"");
      pos9.setText(A[0][8]+"");
      pos10.setText(A[1][0]+"");
      pos11.setText(A[1][1]+"");
      pos12.setText(A[1][2]+"");
      
      pos13.setText(A[0][2]+"");
      pos14.setText(A[0][3]+""); 
      pos15.setText(A[0][4]+"");
      pos16.setText(A[0][5]+"");
      pos17.setText(A[0][6]+"");
      pos18.setText(A[0][7]+"");
      pos19.setText(A[0][8]+"");
      
      
      
      
      
      
      
      
      
    }//GEN-LAST:event_ResolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku9().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Resolver;
    private javax.swing.JTextField pos1;
    private javax.swing.JTextField pos10;
    private javax.swing.JTextField pos11;
    private javax.swing.JTextField pos12;
    private javax.swing.JTextField pos13;
    private javax.swing.JTextField pos14;
    private javax.swing.JTextField pos15;
    private javax.swing.JTextField pos16;
    private javax.swing.JTextField pos17;
    private javax.swing.JTextField pos18;
    private javax.swing.JTextField pos19;
    private javax.swing.JTextField pos2;
    private javax.swing.JTextField pos20;
    private javax.swing.JTextField pos21;
    private javax.swing.JTextField pos22;
    private javax.swing.JTextField pos23;
    private javax.swing.JTextField pos24;
    private javax.swing.JTextField pos25;
    private javax.swing.JTextField pos26;
    private javax.swing.JTextField pos27;
    private javax.swing.JTextField pos28;
    private javax.swing.JTextField pos29;
    private javax.swing.JTextField pos3;
    private javax.swing.JTextField pos30;
    private javax.swing.JTextField pos31;
    private javax.swing.JTextField pos32;
    private javax.swing.JTextField pos33;
    private javax.swing.JTextField pos34;
    private javax.swing.JTextField pos35;
    private javax.swing.JTextField pos36;
    private javax.swing.JTextField pos37;
    private javax.swing.JTextField pos38;
    private javax.swing.JTextField pos39;
    private javax.swing.JTextField pos4;
    private javax.swing.JTextField pos40;
    private javax.swing.JTextField pos41;
    private javax.swing.JTextField pos42;
    private javax.swing.JTextField pos43;
    private javax.swing.JTextField pos44;
    private javax.swing.JTextField pos45;
    private javax.swing.JTextField pos46;
    private javax.swing.JTextField pos47;
    private javax.swing.JTextField pos48;
    private javax.swing.JTextField pos49;
    private javax.swing.JTextField pos5;
    private javax.swing.JTextField pos50;
    private javax.swing.JTextField pos51;
    private javax.swing.JTextField pos52;
    private javax.swing.JTextField pos53;
    private javax.swing.JTextField pos54;
    private javax.swing.JTextField pos55;
    private javax.swing.JTextField pos56;
    private javax.swing.JTextField pos57;
    private javax.swing.JTextField pos58;
    private javax.swing.JTextField pos59;
    private javax.swing.JTextField pos6;
    private javax.swing.JTextField pos60;
    private javax.swing.JTextField pos61;
    private javax.swing.JTextField pos62;
    private javax.swing.JTextField pos63;
    private javax.swing.JTextField pos64;
    private javax.swing.JTextField pos65;
    private javax.swing.JTextField pos66;
    private javax.swing.JTextField pos67;
    private javax.swing.JTextField pos68;
    private javax.swing.JTextField pos69;
    private javax.swing.JTextField pos7;
    private javax.swing.JTextField pos70;
    private javax.swing.JTextField pos71;
    private javax.swing.JTextField pos72;
    private javax.swing.JTextField pos73;
    private javax.swing.JTextField pos74;
    private javax.swing.JTextField pos75;
    private javax.swing.JTextField pos76;
    private javax.swing.JTextField pos77;
    private javax.swing.JTextField pos78;
    private javax.swing.JTextField pos79;
    private javax.swing.JTextField pos8;
    private javax.swing.JTextField pos80;
    private javax.swing.JTextField pos81;
    private javax.swing.JTextField pos9;
    // End of variables declaration//GEN-END:variables
}
